### ISSUE TITLE
[Request] Support for 2-way communication for sendsave

### ISSUE THREAD

**Issue by shadowofdarkness** [akkera102/gba_01_multiboot#1]
I just found this great piece of software that could save me from pulling out and working with a very old (probably around 19+ years old) just to use my Xboo cable with its Parallel Port. So thank you.

I pulled out my xboo cable and connected the appropriate pins to my Raspberry Pi's GPIO pins and after a little fudging around with software I got it to work and can successfully send mb roms to my GBA.

The only problem is I have little use for that normally and would like to use sendsave to read or write saves between a cartridge and the Pi.

The gba mb rom needed is in a archive in step 6 of this post
https://projectpokemon.org/forums/forums/topic/10944-how-to-backup-and-restore-your-gba-save-files/

I don;t know if it will matter for this but the cable I built uses 5 wires and your instructions only use 4 so the extra may be used to 2-way communication and need to be added.

EDIT: I remembered the actual homepage for sendsave
https://www.chishm.com/SendSave/index.html

**Comment by akkera102** [comment]
Thank you for comments on the program about one year ago.

I saw the link URL. I also downloaded the file,
Since there is no source code (technical data), I do not know the connection method.

Another point. Because I don't have passion of GBA homebrew,
I can not write the code. I'm sorry.

Instead I will inform you the newest information I know.
https://www.insidegadgets.com/projects/gbxcart-rw/

> • Backup games ROM to your PC
> • Backup save games to your PC
> • Restore save games from your PC
> • Supports SRAM / Flash / EEPROM for Gameboy Advance cartridges

Probably You need 23$ + Sending money :)

**Comment by shadowofdarkness** [comment]
The edit with the actual homepage included source to sendsave and info on who made xcomms which it relies on. Which would probably be able to find more info on although I'm not sure on source for it.

But I understand that you don't want to work on it. I do have other ways like a NDS flash cart that can also get me saves. I just liked the idea of using the xboo cable plus if it was updated for newer computer hardware it probably could find renewed usage by other people/

**Comment by akkera102** [comment]
When I read the source code, there are probably no technical problems.
SendSave uses libgba, and the source code exists in the devkitpro project (sourceforge).

GBA communication uses REG_SIOCNT, REG_SIODATA32.
Probably wire is fine with 4 pins. You may not need 5 pins.

I understood your passion. I thought what to do...
I think I will make it. Well, it takes time for a week or two.

SendSave_mb.gba in https://www.chishm.com/SendSave/index.html
SendSave_mb.gba will use new my program (raspberry pi).

Wait a while!

**Comment by shadowofdarkness** [comment]
Thank you

**Comment by akkera102** [comment]
I added tool. test game is mario cart(J), mr driller(J), riviera(J). all done.
but Sometimes it fails with a verify check. 
If it fails please try it two or three times.

wire is 4 pins. no need change.

1. at one's own risk.
2. Tool can't action keyboard. you use gameboy button.(L+A+B or R+A+B)
3. Please press the button at the same time. It often happens that timing does not match.

**Comment by shadowofdarkness** [comment]
Wow great work, I just successfully tested it with Pokemon Leaf Green (U) and backup and restoring both worked great after getting the timing right on the button combinations.

**Comment by akkera102** [comment]
thank you for report.
i enjoyed GBA programing after a long time :)
