### ISSUE TITLE
[Request] An update to a newer maintained GPIO library.

### ISSUE THREAD

**Issue by shadowofdarkness** [akkera102/gba_01_multiboot#2]
I have been using this ever since you made in compatible with SendSave and still get use of it to this day. So thank you for the work you put into it.

I was hoping that you would make it usable with libgpiod which from my understanding is how part of the Linux 5.5 kernel and with WiringPi being deprecated and hard to get without finding a old mirror of the latest deb. Which I found out after a clean install awhile ago and how I found out the newest 

It would be nice to move to a maintained GPIO library for ease of setting up on newer Raspberry Pi's

I do know about the gba_03_multiboot repo but I just asked here as that rewrite never did get SendSave which is important to me.

**Comment by akkera102** [comment]
Hmm, very sad. I understood that WiringPi was no longer supported.

After some research, a possible replacement library is pigpio. Please wait about a week. I'll remake it.

Thank you for using sendsave.

**Comment by shadowofdarkness** [comment]
Thank you

**Comment by akkera102** [comment]
Changed to Pigpio Library. This should be fine for a while. :)

**Comment by shadowofdarkness** [comment]
Thanks I tested both multiboot and sendsave and they both worked.
